use ct_pull_image in shell scripts
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

diff --git a/tests/test-lib/image_availability b/tests/test-lib/image_availability
--- a/tests/test-lib/image_availability
+++ b/tests/test-lib/image_availability
@@ -5,14 +5,26 @@ set -e
 . test-lib.sh
 
 # This should succeed
-if ! ct_check_image_availability quay.io/centos7/ruby-27-centos7; then
+if ! ct_pull_image quay.io/centos7/ruby-27-centos7; then
   echo "image_availability test failed"
   false
 fi
 
 # This should fail
-if ct_check_image_availability quay.io/centos7/ruby-24-centos7; then
+if ct_pull_image quay.io/centos7/ruby-24-centos7; then
   echo "image_availability test failed"
+  false
+fi
+
+# This should succeed
+if ! ct_check_image_availability quay.io/centos7/ruby-27-centos7; then
+  echo "check_image_availability test failed"
+  false
+fi
+
+# This should fail
+if ct_check_image_availability quay.io/centos7/ruby-24-centos7; then
+  echo "check_image_availability test failed"
   false
 fi
 
